#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine
#
# Install nginx on your web-01
# Nginx should be listening on port 80
# When querying Nginx root / with a GET reques curl returns Hello World!

apt-get update
apt-get install nginx
ufw allow 'Nginx full'
sudo echo "Hello World!" > /var/www/html/index.html
nginx -s reload
