#!/usr/bin/env bash
# Get the PIDs of processes whose name contains the word "bash"

pids=$(pgrep bash)

# Loop through each PID and display the PID and process name
for pid in $pids;
do
    process_name=$(ps -p "$pid" -o comm=)
    echo "$pid $process_name"
done

