#!/usr/bin/env bash
# script that displays To infinity and beyond indefinitely.

function clean {
    echo "I am invincible!!!"
}

trap clean SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
