#!/usr/bin/env bash
# a script that brints a give string a number of times
#and at iteration 9 prints a different string

i=0

while [ $i -le 9 ];
do 
    if [ $i -eq 9 ]
    then
        echo "Hi"
    fi
    echo $"Best School"
    (( i ++))
done
