#!/usr/bin/env bash
# a script that brints a give string a number of times
#and at iteration 4 and 8 prints a different string

i=0

while [ $i -le 9 ];
do 
    if [ $i == 3 ]
    then
        echo "bad luck"
    elif [ $i -eq 7 ]
    then
        echo "good luck"
    else
        echo $"Best School"
    fi
    (( i ++))
done
