#!/usr/bin/env bash
# Configures an Ubuntu server with specific IP addresses for `localhost` and `facebook.com`

sudo cp /etc/hosts /tmp/temp_file

# Modify the temporary file as needed
sudo sed -i.bak 's/^127.*localhost$/127.0.0.2 localhost/' /tmp/temp_file
if grep -q '^127\.0\.0\.1 facebook.com$' /tmp/temp_file; then
    # Modify the line if it's present
    sudo sed -i.bak 's/^127\.0\.0\.1 facebook.com$/8.8.8.8 facebook.com/' /tmp/temp_file
    echo "Modified existing entry for facebook.com."
else
    # Add a new line if the entry is not present
    echo "8.8.8.8 facebook.com" | sudo tee -a /tmp/temp_file > /dev/null
    echo "Added a new entry for facebook.com."
fi

sudo cp -f /tmp/temp_file /etc/hosts

 # Clean up the temporary files
sudo rm /tmp/temp_file /tmp/temp_file.bak
